print("-"*100)
name=input("Enter your name-")
print(name)
roll_no=input("Enter your roll no-")
print(roll_no)
gr_no=input("Enter your gr no-")
print(gr_no)
branch=input("Enter your branch-")
print(branch)
division=input("Enter your division-")
print(division)
